root: true
extends:
    - "eslint:recommended"
    - "plugin:@typescript-eslint/recommended"
    - "plugin:@typescript-eslint/eslint-recommended"
    - "plugin:@typescript-eslint/recommended-requiring-type-checking"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaFeatures:
        jsx: true
    tsconfigRootDir: { { path | dirname } }
    project: "./tsconfig.json"

plugins:
    - "@typescript-eslint"
    - react
    - react-hooks
ignorePatterns:
    - "dist/*"
rules:
    indent:
        - warn
        - 4
    quotes:
        - error
        - double
    semi:
        - error
        - always
    no-unused-vars: off
    prefer-const: off
    "@typescript-eslint/no-unused-vars": off
    "@typescript-eslint/prefer-as-const": off
    "@typescript-eslint/no-unsafe-assignment": off
    "@typescript-eslint/no-invalid-this": 2

    no-var: off
